version: "3.4"
services:
    webserver:
      image: nginx:latest
      container_name: awesome-site
      volumes:
          - ./conf/nginx.conf:/etc/nginx/nginx.conf
          - ./docs/:/usr/share/nginx/html
      ports:
          - "80:80"
      restart : always
